#encoding: utf-8
card1 = Card.create(word: 'apple', definition: 'yummy fruit, usually red or green', language: 'English', picture: 'http://eofdreams.com/data_images/dreams/apple/apple-05.jpg')
card2 = Card.create(word: '苹果', definition: '一种常见的水果', language: 'Chinese', picture: 'http://eofdreams.com/data_images/dreams/apple/apple-05.jpg')
card3 = Card.create(word: '元宵', definition: '一种传统的中国食物,一般在元宵节吃', language: 'Chinese', picture: 'http://windhorsetour.com/sites/windhorsetour.com/files/styles/large/public/yuanxiao-or-tangyuan.jpg?itok=_J3ay658')
card4 = Card.create(word: '打的', definition: '乘坐出租车', language: 'Chinese', picture: 'http://img.jillkonrath.com/hs-fs/hub/110248/file-16520267-jpg/images/blogs/why-i-cant-catch-a-taxi-04-19-2012-hail-cab.jpg')
card5 = Card.create(word: '安检', definition: '安全检查', language: 'Chinese', picture: 'http://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Berlin_Sch%C3%B6nefeld_Airport_metal_detectors.jpg/220px-Berlin_Sch%C3%B6nefeld_Airport_metal_detectors.jpg')
card6 = Card.create(word: '介绍', definition: '沟通使了解', language: 'Chinese', picture: 'http://blog.contactually.com/wp-content/uploads/2013/01/introduction.jpg')
card7 = Card.create(word: '驴友', definition: '一起旅游的朋友', language: 'Chinese', picture: 'https://www.cascada.travel/sites/default/files/styles/large/public/media/Activity/Hiking/galery_wtrek_complete1.jpg')
card8 = Card.create(word: 'surfing', definition: 'the act or sport of riding water on a board', language: 'English', picture: 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Surfer_at_the_Cayucos_Pier%2C_Cayucos%2C_CA.jpg/220px-Surfer_at_the_Cayucos_Pier%2C_Cayucos%2C_CA.jpg')
card9 = Card.create(word: 'awesome', definition: 'perfect; fabulous; great', language: 'English', picture: 'http://www.korpg.com/blog/wp-content/uploads/2012/05/that_was_awesome.jpg')
card10 = Card.create(word: 'computer', definition: 'an electronic device designed to accept data and perform functions', language: 'English', picture: 'http://rogelioalegrid.files.wordpress.com/2013/04/9353062-cartoon-smiling-desktop-computer-vector-illustration.jpg')
card11 = Card.create(word: 'selfie', definition: 'a self-portrait photograph, typically taken with a hand-held digital camera or camera phone.', language: 'English', picture: 'http://bobritzema.files.wordpress.com/2013/12/justin-bieber-2013-selfie.jpg?w=275&h=300')
card12 = Card.create(word: 'early bird', definition: 'someone who gets up early', language: 'English', picture: 'http://shaikhology.com/wp-content/uploads/2013/05/early_brid_coffee-232x300.jpg')
card13 = Card.create(word: 'caballero', definition: 'el que se comporta noble o anda a caballo', language: 'Spanish', picture: 'http://radiodad.com/mikeaustin/wp-content/uploads/2012/03/The-Knight1.jpg')
card14 = Card.create(word: 'camión', definition: 'vehículo automóvil grande, de cuatro o más ruedas', language: 'Spanish', picture: 'http://image.made-in-china.com/2f0j00wegaOvsBkZpr/FAW-J5P-6x4-Dump-Truck-CA3252-.jpg')
card15 = Card.create(word: 'arbóreo', definition: 'del árbol o relativo a él', language: 'Spanish', picture: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Little_Elk_Lake2.jpg/284px-Little_Elk_Lake2.jpg')

card1.sentences << Sentence.create(content: 'My brother eats apples every day.', teacher: 1, language: 'English', points: 8)
card2.sentences << Sentence.create(content: '我爱吃苹果.', teacher: 1, language: 'Chinese', points: 1)
card3.sentences << Sentence.create(content: '正月十五是元宵节，我吃了一碗元宵。', teacher: 1, language: 'Chinese', points: 5)
card4.sentences << Sentence.create(content: '走路太累了，地铁太挤了，公交太慢了，还是打的最好。', teacher: 1, language: 'Chinese', points: 0)
card5.sentences << Sentence.create(content: '机场的安检好严好慢，每次去机场安检都要花半小时。', teacher: 1, language: 'Chinese', points: 0)
card6.sentences << Sentence.create(content: '你帮我介绍一下北京有什么好玩的。', teacher: 1, language: 'Chinese', points: 2)
card7.sentences << Sentence.create(content: '我约了一群驴友去登珠穆朗玛峰。', teacher: 1, language: 'Chinese', points: 5)
card9.sentences << Sentence.create(content: 'This is an awesome way to make money.', teacher: 1, language: 'English', points: 1)
card10.sentences << Sentence.create(content: 'I like to play video games on my computer.', teacher: 1, language: 'English', points: 3)
card11.sentences << Sentence.create(content: 'After coming back from school, my daughter spends half her day taking selfies in bed.', teacher: 1, language: 'English', points: 6)
card12.sentences << Sentence.create(content: 'Mary is an early bird. She gets up around five o-clock every morning.', teacher: 1, language: 'English', points: 28)
card13.sentences << Sentence.create(content: 'El caballero tiene un gato en sus pantilones.', teacher: 1, language: 'English', points: 1)
card14.sentences << Sentence.create(content: 'Mi padre conduce un camión.', teacher: 1, language: 'English', points: 3)
card15.sentences << Sentence.create(content: 'La selva y el parque son muy arbóreo.', teacher: 1, language: 'English', points: 2)
